# Generated by Django 5.2.4 on 2025-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='BC436C497514', editable=False, max_length=100, unique=True),
        ),
    ]
