# Generated by Django 5.2.4 on 2025-07-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
